"""initial schema

Revision ID: 0001
Revises:
"""

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'agent',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('owner_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('animal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('palette', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('seed', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('persona_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('model_brain', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('model_worker', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('main_conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_owner_user_id'), ['owner_user_id'], unique=False)

    op.create_table(
        'device',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('apns_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('ntfy_topic', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column('last_seen', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_device_user_id'), ['user_id'], unique=False)

    op.create_table(
        'usage_snapshot',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('taken_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column('window', sa.Enum('five_hour', 'weekly', name='usagewindow'), nullable=False),
        sa.Column('used_pct', sa.Float(), nullable=False),
        sa.Column('resets_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('usage_snapshot', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usage_snapshot_taken_at'), ['taken_at'], unique=False)

    op.create_table(
        'conversation',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('kind', sa.Enum('main', 'side', name='conversationkind'), nullable=False),
        sa.Column('parent_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('brain_session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['agent_id'],
            ['agent.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_conversation_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_conversation_task_id'), ['task_id'], unique=False)

    op.create_table(
        'schedule',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('cron', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('tz', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            'location', sa.Enum('brain', 'nuc', 'cloud', name='schedulelocation'), nullable=False
        ),
        sa.Column('prompt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('paused', sa.Boolean(), nullable=False),
        sa.Column('builtin', sa.Boolean(), nullable=False),
        sa.Column('deadline_minutes', sa.Integer(), nullable=True),
        sa.Column('last_run_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column('next_run_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['agent_id'],
            ['agent.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedule_agent_id'), ['agent_id'], unique=False)

    op.create_table(
        'task',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('location', sa.Enum('nuc', 'cloud', name='tasklocation'), nullable=False),
        sa.Column(
            'state',
            sa.Enum(
                'queued',
                'starting',
                'working',
                'needs_you',
                'done',
                'failed',
                'stopped',
                'silent',
                'unknown',
                name='taskstate',
            ),
            nullable=False,
        ),
        sa.Column('queued_reason', sa.Enum('cap', 'usage', name='queuedreason'), nullable=True),
        sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('cloud_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('remote_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('repo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('branch', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('worktree', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            'origin', sa.Enum('marcel', 'adopted', 'schedule', name='taskorigin'), nullable=False
        ),
        sa.Column('parent_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('schedule_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('waiting_for', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column('last_activity_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column('expected_by', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.Column('archived_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['agent_id'],
            ['agent.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_task_state'), ['state'], unique=False)

    op.create_table(
        'approval',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('tool', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('detail', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('artifact_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            'state',
            sa.Enum('open', 'approved', 'denied', 'expired', name='approvalstate'),
            nullable=False,
        ),
        sa.Column('answered_via', sa.Enum('app', 'terminal', name='answeredvia'), nullable=True),
        sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.Column('answered_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ['task_id'],
            ['task.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approval_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approval_task_id'), ['task_id'], unique=False)

    op.create_table(
        'artifact',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            'kind',
            sa.Enum('pr', 'branch', 'doc', 'file', 'dashboard', 'link', name='artifactkind'),
            nullable=False,
        ),
        sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('content_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('size_bytes', sa.Integer(), nullable=True),
        sa.Column('trusted', sa.Boolean(), nullable=False),
        sa.Column('self_change', sa.Boolean(), nullable=False),
        sa.Column('meta_json', sa.JSON(), nullable=False),
        sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['task_id'],
            ['task.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artifact_task_id'), ['task_id'], unique=False)

    op.create_table(
        'message',
        sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('conversation_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('role', sa.Enum('user', 'agent', 'system', name='messagerole'), nullable=False),
        sa.Column(
            'kind',
            sa.Enum('text', 'milestone', 'approval', 'quote', name='messagekind'),
            nullable=False,
        ),
        sa.Column('body_json', sa.JSON(), nullable=False),
        sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('client_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['conversation_id'],
            ['conversation.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_client_id'), ['client_id'], unique=False)
        batch_op.create_index(
            batch_op.f('ix_message_conversation_id'), ['conversation_id'], unique=False
        )
        batch_op.create_index(batch_op.f('ix_message_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_task_id'), ['task_id'], unique=False)

    op.create_table(
        'task_event',
        sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('seq', sa.Integer(), nullable=False),
        sa.Column(
            'type',
            sa.Enum(
                'text',
                'tool_call',
                'tool_result',
                'diff',
                'permission',
                'subagent_start',
                'subagent_stop',
                'error',
                'raw',
                'state',
                'progress',
                'artifact',
                'note',
                name='taskeventtype',
            ),
            nullable=False,
        ),
        sa.Column('data_json', sa.JSON(), nullable=False),
        sa.Column('at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ['task_id'],
            ['task.id'],
        ),
        sa.PrimaryKeyConstraint('task_id', 'seq'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_event')
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_task_id'))
        batch_op.drop_index(batch_op.f('ix_message_created_at'))
        batch_op.drop_index(batch_op.f('ix_message_conversation_id'))
        batch_op.drop_index(batch_op.f('ix_message_client_id'))

    op.drop_table('message')
    with op.batch_alter_table('artifact', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artifact_task_id'))

    op.drop_table('artifact')
    with op.batch_alter_table('approval', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approval_task_id'))
        batch_op.drop_index(batch_op.f('ix_approval_request_id'))

    op.drop_table('approval')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_state'))
        batch_op.drop_index(batch_op.f('ix_task_agent_id'))

    op.drop_table('task')
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedule_agent_id'))

    op.drop_table('schedule')
    with op.batch_alter_table('conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_conversation_task_id'))
        batch_op.drop_index(batch_op.f('ix_conversation_agent_id'))

    op.drop_table('conversation')
    with op.batch_alter_table('usage_snapshot', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usage_snapshot_taken_at'))

    op.drop_table('usage_snapshot')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_token_hash'))

    op.drop_table('device')
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_owner_user_id'))

    op.drop_table('agent')
    # ### end Alembic commands ###
