"""Promote a proven script into a durable ``register(marcel)`` extension.

The co-work loop's second half (F3): a script Marcel proved out — typically
via :mod:`code_exec` — is rendered into a ``register(marcel)`` extension
module, written into the zoo's ``extensions/`` tree, committed, and deployed
via the **one legal restart path** (``request_restart()`` → host systemd →
watchdog). Never a direct restart (``.claude/rules/self-modification.md``).

Recoverability: the extension is committed as its own zoo commit *before* the
restart is requested, so ``git revert`` cleanly undoes it. A promoted
extension that fails to import is isolated by the loader
(:func:`marcel_core.plugin.extension.load_extensions`), so a bad promotion
degrades to an inert file, never a restart loop.
"""

from __future__ import annotations

import logging
import re
import subprocess
from pathlib import Path

from pydantic_ai import RunContext

from marcel_core.harness.context import MarcelDeps

log = logging.getLogger(__name__)

_EXT_NAME = re.compile(r'^[a-z][a-z0-9_]*$')
_TOOL_ID = re.compile(r'^[a-z][a-z0-9_]*\.[a-z][a-z0-9_]*$')


class PromotionError(Exception):
    """Raised when a promotion cannot proceed (validation / git / no zoo)."""


def render_tool_extension(tool_id: str, code: str, description: str = '') -> str:
    """Render a ``register(marcel)`` module exposing *tool_id* from *code*.

    *code* is the **async handler body** — it receives ``params: dict`` and
    ``user_slug: str`` in scope and must ``return`` a string. It is indented
    into the generated handler verbatim.
    """
    _family, action = tool_id.split('.')
    body_lines = code.splitlines() or ['return ""']
    indented = '\n'.join(('        ' + line) if line.strip() else '' for line in body_lines)
    desc = (description or f'Promoted extension {tool_id}').replace('"""', "'''")
    return (
        f'"""{desc}\n\n'
        'Auto-generated by promote_extension from a proven script. Edit here or re-promote.\n'
        '"""\n\n'
        'from marcel_sdk import get_logger\n\n'
        'log = get_logger(__name__)\n\n\n'
        'def register(marcel):\n'
        f'    @marcel.tool("{tool_id}")\n'
        f'    async def {action}(params: dict, user_slug: str) -> str:\n'
        f'{indented}\n'
    )


def _git(cwd: Path, *args: str) -> subprocess.CompletedProcess:
    return subprocess.run(['git', '-C', str(cwd), *args], capture_output=True, text=True, check=True)


def _kernel_head_sha() -> str:
    """Return the marcel kernel repo's HEAD SHA (the watchdog rollback anchor)."""
    repo_root = Path(__file__).resolve().parents[3]
    return _git(repo_root, 'rev-parse', 'HEAD').stdout.strip()


def promote_tool_extension(
    *,
    tool_id: str,
    code: str,
    description: str = '',
    name: str | None = None,
    zoo_dir: Path | None = None,
    deploy: bool = True,
) -> Path:
    """Promote *code* into a ``register(marcel)`` tool extension in the zoo.

    Validates the ids, renders + compile-checks the module, writes
    ``<zoo>/extensions/<name>/__init__.py``, commits the zoo, and (when
    ``deploy``) requests a restart via the flag path. Returns the written
    path; raises :class:`PromotionError` on any validation / git failure.
    """
    from marcel_core.config import settings

    if not _TOOL_ID.match(tool_id):
        raise PromotionError(f"invalid tool_id {tool_id!r} — must be 'family.action' (lowercase segments)")
    ext_name = name or tool_id.split('.')[0]
    if not _EXT_NAME.match(ext_name):
        raise PromotionError(f'invalid extension name {ext_name!r} — must be a lowercase slug')

    zoo = zoo_dir if zoo_dir is not None else settings.zoo_dir
    if zoo is None:
        raise PromotionError('MARCEL_ZOO_DIR is not set — nowhere to promote to')

    module_code = render_tool_extension(tool_id, code, description)
    try:
        compile(module_code, f'<promote:{ext_name}>', 'exec')
    except SyntaxError as exc:
        raise PromotionError(f'promoted code does not compile: {exc}') from exc

    ext_dir = zoo / 'extensions' / ext_name
    ext_dir.mkdir(parents=True, exist_ok=True)
    path = ext_dir / '__init__.py'
    path.write_text(module_code, encoding='utf-8')

    # Recoverable: commit the change before requesting any restart.
    try:
        _git(zoo, 'add', f'extensions/{ext_name}/__init__.py')
        _git(zoo, 'commit', '-m', f'promote: {tool_id} — auto-promoted extension')
    except subprocess.CalledProcessError as exc:
        raise PromotionError(f'failed to commit the extension into the zoo: {exc.stderr or exc}') from exc

    if deploy:
        from marcel_core.watchdog.flags import request_restart

        request_restart(_kernel_head_sha())
        log.info('promoted %s → %s; restart requested via flag', tool_id, path)
    return path


async def promote_extension(ctx: RunContext[MarcelDeps], tool_id: str, code: str, description: str = '') -> str:
    """Promote a proven script into a durable ``register(marcel)`` extension.

    Turns a one-off script into a permanent capability: the ``code`` becomes
    the body of an async toolkit handler ``(params, user_slug) -> str`` under
    ``tool_id`` (``"family.action"``), written into the zoo and deployed on
    the next redeploy via the restart-flag path.

    Args:
        ctx: Agent context.
        tool_id: The handler id, ``"family.action"`` (lowercase).
        code: The async handler body; ``params`` and ``user_slug`` are in
            scope and it must ``return`` a string.
        description: Optional one-line description for the module docstring.

    Returns:
        A confirmation with the written path, or an error message.
    """
    log.info('[promote_extension] user=%s tool_id=%s', ctx.deps.user_slug, tool_id)
    try:
        path = promote_tool_extension(tool_id=tool_id, code=code, description=description)
    except PromotionError as exc:
        return f'Promotion failed: {exc}'
    except Exception as exc:  # noqa: BLE001 — surface any unexpected failure to the model, not a crash
        log.exception('[promote_extension] unexpected failure')
        return f'Promotion failed unexpectedly: {exc}'
    return (
        f'Promoted {tool_id} → {path}. Committed to the zoo and requested a restart via the '
        f'flag path; the new extension loads on the next redeploy.'
    )
